/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * CO2 Emissions API (DEU, Climate TRACE)
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './fetcher';
export type ListSectors200 = {
  sectors: string[];
};

export type TopOwnersParams = {
year: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type TopOwners200DataItem = {
  owner: string;
  emissions_quantity: number;
  source_count: number;
};

export type TopOwners200 = {
  data: TopOwners200DataItem[];
};

export type OwnerTrend200DataItem = {
  year: number;
  emissions_quantity: number;
  source_count: number;
};

export type OwnerTrend200 = {
  owner: string;
  data: OwnerTrend200DataItem[];
};

export type SectorTimeseries200DataItem = {
  year: number;
  sector: string;
  emissions_quantity: number;
};

export type SectorTimeseries200 = {
  data: SectorTimeseries200DataItem[];
};

export type SectorSubsectors200DataItem = {
  subsector: string;
  year: number;
  emissions_quantity: number;
};

export type SectorSubsectors200 = {
  data: SectorSubsectors200DataItem[];
};

export type TopSourcesParams = {
year: number;
};

export type TopSources200DataItem = {
  source_id: number;
  /** @nullable */
  source_name: string | null;
  /** @nullable */
  lat: number | null;
  /** @nullable */
  lon: number | null;
  emissions_quantity: number;
  rank: number;
};

export type TopSources200 = {
  data: TopSources200DataItem[];
};

export type SubsectorSourcesParams = {
year: number;
};

export type SubsectorSources200DataItem = {
  source_id: number;
  /** @nullable */
  source_name: string | null;
  /** @nullable */
  lat: number | null;
  /** @nullable */
  lon: number | null;
  emissions_quantity: number;
};

export type SubsectorSources200 = {
  data: SubsectorSources200DataItem[];
};

export type SourceOwnership200DataItem = {
  /** @nullable */
  parent_name: string | null;
  /** @nullable */
  parent_entity_type: string | null;
  /** @nullable */
  parent_registration_country: string | null;
  /** @nullable */
  overall_share_percent: number | null;
  /** @nullable */
  immediate_source_owner: string | null;
  /** @nullable */
  ownership_path: string | null;
};

export type SourceOwnership200 = {
  data: SourceOwnership200DataItem[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getHealthResponse200 = {
  data: void
  status: 200
}

export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {




  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {

  return customFetch<getHealthResponse>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type listSectorsResponse200 = {
  data: ListSectors200
  status: 200
}

export type listSectorsResponseSuccess = (listSectorsResponse200) & {
  headers: Headers;
};
;

export type listSectorsResponse = (listSectorsResponseSuccess)

export const getListSectorsUrl = () => {




  return `/sectors`
}

export const listSectors = async ( options?: RequestInit): Promise<listSectorsResponse> => {

  return customFetch<listSectorsResponse>(getListSectorsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSectorsQueryKey = () => {
    return [
    `/sectors`
    ] as const;
    }


export const getListSectorsQueryOptions = <TData = Awaited<ReturnType<typeof listSectors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSectorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSectors>>> = ({ signal }) => listSectors({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSectorsQueryResult = NonNullable<Awaited<ReturnType<typeof listSectors>>>
export type ListSectorsQueryError = unknown


export function useListSectors<TData = Awaited<ReturnType<typeof listSectors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSectors>>,
          TError,
          Awaited<ReturnType<typeof listSectors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSectors<TData = Awaited<ReturnType<typeof listSectors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSectors>>,
          TError,
          Awaited<ReturnType<typeof listSectors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSectors<TData = Awaited<ReturnType<typeof listSectors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListSectors<TData = Awaited<ReturnType<typeof listSectors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSectorsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type topOwnersResponse200 = {
  data: TopOwners200
  status: 200
}

export type topOwnersResponseSuccess = (topOwnersResponse200) & {
  headers: Headers;
};
;

export type topOwnersResponse = (topOwnersResponseSuccess)

export const getTopOwnersUrl = (params: TopOwnersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/owners?${stringifiedParams}` : `/owners`
}

export const topOwners = async (params: TopOwnersParams, options?: RequestInit): Promise<topOwnersResponse> => {

  return customFetch<topOwnersResponse>(getTopOwnersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTopOwnersQueryKey = (params?: TopOwnersParams,) => {
    return [
    `/owners`, ...(params ? [params] : [])
    ] as const;
    }


export const getTopOwnersQueryOptions = <TData = Awaited<ReturnType<typeof topOwners>>, TError = unknown>(params: TopOwnersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTopOwnersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof topOwners>>> = ({ signal }) => topOwners(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TopOwnersQueryResult = NonNullable<Awaited<ReturnType<typeof topOwners>>>
export type TopOwnersQueryError = unknown


export function useTopOwners<TData = Awaited<ReturnType<typeof topOwners>>, TError = unknown>(
 params: TopOwnersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof topOwners>>,
          TError,
          Awaited<ReturnType<typeof topOwners>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTopOwners<TData = Awaited<ReturnType<typeof topOwners>>, TError = unknown>(
 params: TopOwnersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof topOwners>>,
          TError,
          Awaited<ReturnType<typeof topOwners>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTopOwners<TData = Awaited<ReturnType<typeof topOwners>>, TError = unknown>(
 params: TopOwnersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTopOwners<TData = Awaited<ReturnType<typeof topOwners>>, TError = unknown>(
 params: TopOwnersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topOwners>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTopOwnersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type ownerTrendResponse200 = {
  data: OwnerTrend200
  status: 200
}

export type ownerTrendResponseSuccess = (ownerTrendResponse200) & {
  headers: Headers;
};
;

export type ownerTrendResponse = (ownerTrendResponseSuccess)

export const getOwnerTrendUrl = (owner: string,) => {




  return `/owners/${owner}/trend`
}

export const ownerTrend = async (owner: string, options?: RequestInit): Promise<ownerTrendResponse> => {

  return customFetch<ownerTrendResponse>(getOwnerTrendUrl(owner),
  {
    ...options,
    method: 'GET'


  }
);}





export const getOwnerTrendQueryKey = (owner: string,) => {
    return [
    `/owners/${owner}/trend`
    ] as const;
    }


export const getOwnerTrendQueryOptions = <TData = Awaited<ReturnType<typeof ownerTrend>>, TError = unknown>(owner: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOwnerTrendQueryKey(owner);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ownerTrend>>> = ({ signal }) => ownerTrend(owner, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: owner !== null && owner !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OwnerTrendQueryResult = NonNullable<Awaited<ReturnType<typeof ownerTrend>>>
export type OwnerTrendQueryError = unknown


export function useOwnerTrend<TData = Awaited<ReturnType<typeof ownerTrend>>, TError = unknown>(
 owner: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ownerTrend>>,
          TError,
          Awaited<ReturnType<typeof ownerTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOwnerTrend<TData = Awaited<ReturnType<typeof ownerTrend>>, TError = unknown>(
 owner: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ownerTrend>>,
          TError,
          Awaited<ReturnType<typeof ownerTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOwnerTrend<TData = Awaited<ReturnType<typeof ownerTrend>>, TError = unknown>(
 owner: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOwnerTrend<TData = Awaited<ReturnType<typeof ownerTrend>>, TError = unknown>(
 owner: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ownerTrend>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOwnerTrendQueryOptions(owner,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type sectorTimeseriesResponse200 = {
  data: SectorTimeseries200
  status: 200
}

export type sectorTimeseriesResponseSuccess = (sectorTimeseriesResponse200) & {
  headers: Headers;
};
;

export type sectorTimeseriesResponse = (sectorTimeseriesResponseSuccess)

export const getSectorTimeseriesUrl = () => {




  return `/sectors/timeseries`
}

export const sectorTimeseries = async ( options?: RequestInit): Promise<sectorTimeseriesResponse> => {

  return customFetch<sectorTimeseriesResponse>(getSectorTimeseriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSectorTimeseriesQueryKey = () => {
    return [
    `/sectors/timeseries`
    ] as const;
    }


export const getSectorTimeseriesQueryOptions = <TData = Awaited<ReturnType<typeof sectorTimeseries>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectorTimeseriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectorTimeseries>>> = ({ signal }) => sectorTimeseries({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectorTimeseriesQueryResult = NonNullable<Awaited<ReturnType<typeof sectorTimeseries>>>
export type SectorTimeseriesQueryError = unknown


export function useSectorTimeseries<TData = Awaited<ReturnType<typeof sectorTimeseries>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectorTimeseries>>,
          TError,
          Awaited<ReturnType<typeof sectorTimeseries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectorTimeseries<TData = Awaited<ReturnType<typeof sectorTimeseries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectorTimeseries>>,
          TError,
          Awaited<ReturnType<typeof sectorTimeseries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectorTimeseries<TData = Awaited<ReturnType<typeof sectorTimeseries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSectorTimeseries<TData = Awaited<ReturnType<typeof sectorTimeseries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorTimeseries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectorTimeseriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type sectorSubsectorsResponse200 = {
  data: SectorSubsectors200
  status: 200
}

export type sectorSubsectorsResponseSuccess = (sectorSubsectorsResponse200) & {
  headers: Headers;
};
;

export type sectorSubsectorsResponse = (sectorSubsectorsResponseSuccess)

export const getSectorSubsectorsUrl = (sector: string,) => {




  return `/sectors/${sector}/subsectors`
}

export const sectorSubsectors = async (sector: string, options?: RequestInit): Promise<sectorSubsectorsResponse> => {

  return customFetch<sectorSubsectorsResponse>(getSectorSubsectorsUrl(sector),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSectorSubsectorsQueryKey = (sector: string,) => {
    return [
    `/sectors/${sector}/subsectors`
    ] as const;
    }


export const getSectorSubsectorsQueryOptions = <TData = Awaited<ReturnType<typeof sectorSubsectors>>, TError = unknown>(sector: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSectorSubsectorsQueryKey(sector);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sectorSubsectors>>> = ({ signal }) => sectorSubsectors(sector, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: sector !== null && sector !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SectorSubsectorsQueryResult = NonNullable<Awaited<ReturnType<typeof sectorSubsectors>>>
export type SectorSubsectorsQueryError = unknown


export function useSectorSubsectors<TData = Awaited<ReturnType<typeof sectorSubsectors>>, TError = unknown>(
 sector: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectorSubsectors>>,
          TError,
          Awaited<ReturnType<typeof sectorSubsectors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectorSubsectors<TData = Awaited<ReturnType<typeof sectorSubsectors>>, TError = unknown>(
 sector: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sectorSubsectors>>,
          TError,
          Awaited<ReturnType<typeof sectorSubsectors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSectorSubsectors<TData = Awaited<ReturnType<typeof sectorSubsectors>>, TError = unknown>(
 sector: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSectorSubsectors<TData = Awaited<ReturnType<typeof sectorSubsectors>>, TError = unknown>(
 sector: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sectorSubsectors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSectorSubsectorsQueryOptions(sector,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type topSourcesResponse200 = {
  data: TopSources200
  status: 200
}

export type topSourcesResponseSuccess = (topSourcesResponse200) & {
  headers: Headers;
};
;

export type topSourcesResponse = (topSourcesResponseSuccess)

export const getTopSourcesUrl = (subsector: string,
    params: TopSourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/subsectors/${subsector}/top?${stringifiedParams}` : `/subsectors/${subsector}/top`
}

export const topSources = async (subsector: string,
    params: TopSourcesParams, options?: RequestInit): Promise<topSourcesResponse> => {

  return customFetch<topSourcesResponse>(getTopSourcesUrl(subsector,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTopSourcesQueryKey = (subsector: string,
    params?: TopSourcesParams,) => {
    return [
    `/subsectors/${subsector}/top`, ...(params ? [params] : [])
    ] as const;
    }


export const getTopSourcesQueryOptions = <TData = Awaited<ReturnType<typeof topSources>>, TError = unknown>(subsector: string,
    params: TopSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTopSourcesQueryKey(subsector,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof topSources>>> = ({ signal }) => topSources(subsector,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subsector !== null && subsector !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TopSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof topSources>>>
export type TopSourcesQueryError = unknown


export function useTopSources<TData = Awaited<ReturnType<typeof topSources>>, TError = unknown>(
 subsector: string,
    params: TopSourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof topSources>>,
          TError,
          Awaited<ReturnType<typeof topSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTopSources<TData = Awaited<ReturnType<typeof topSources>>, TError = unknown>(
 subsector: string,
    params: TopSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof topSources>>,
          TError,
          Awaited<ReturnType<typeof topSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTopSources<TData = Awaited<ReturnType<typeof topSources>>, TError = unknown>(
 subsector: string,
    params: TopSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTopSources<TData = Awaited<ReturnType<typeof topSources>>, TError = unknown>(
 subsector: string,
    params: TopSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof topSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTopSourcesQueryOptions(subsector,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type subsectorSourcesResponse200 = {
  data: SubsectorSources200
  status: 200
}

export type subsectorSourcesResponseSuccess = (subsectorSourcesResponse200) & {
  headers: Headers;
};
;

export type subsectorSourcesResponse = (subsectorSourcesResponseSuccess)

export const getSubsectorSourcesUrl = (subsector: string,
    params: SubsectorSourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/subsectors/${subsector}/sources?${stringifiedParams}` : `/subsectors/${subsector}/sources`
}

export const subsectorSources = async (subsector: string,
    params: SubsectorSourcesParams, options?: RequestInit): Promise<subsectorSourcesResponse> => {

  return customFetch<subsectorSourcesResponse>(getSubsectorSourcesUrl(subsector,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSubsectorSourcesQueryKey = (subsector: string,
    params?: SubsectorSourcesParams,) => {
    return [
    `/subsectors/${subsector}/sources`, ...(params ? [params] : [])
    ] as const;
    }


export const getSubsectorSourcesQueryOptions = <TData = Awaited<ReturnType<typeof subsectorSources>>, TError = unknown>(subsector: string,
    params: SubsectorSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubsectorSourcesQueryKey(subsector,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof subsectorSources>>> = ({ signal }) => subsectorSources(subsector,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subsector !== null && subsector !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubsectorSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof subsectorSources>>>
export type SubsectorSourcesQueryError = unknown


export function useSubsectorSources<TData = Awaited<ReturnType<typeof subsectorSources>>, TError = unknown>(
 subsector: string,
    params: SubsectorSourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subsectorSources>>,
          TError,
          Awaited<ReturnType<typeof subsectorSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubsectorSources<TData = Awaited<ReturnType<typeof subsectorSources>>, TError = unknown>(
 subsector: string,
    params: SubsectorSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subsectorSources>>,
          TError,
          Awaited<ReturnType<typeof subsectorSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubsectorSources<TData = Awaited<ReturnType<typeof subsectorSources>>, TError = unknown>(
 subsector: string,
    params: SubsectorSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSubsectorSources<TData = Awaited<ReturnType<typeof subsectorSources>>, TError = unknown>(
 subsector: string,
    params: SubsectorSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subsectorSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubsectorSourcesQueryOptions(subsector,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type sourceOwnershipResponse200 = {
  data: SourceOwnership200
  status: 200
}

export type sourceOwnershipResponseSuccess = (sourceOwnershipResponse200) & {
  headers: Headers;
};
;

export type sourceOwnershipResponse = (sourceOwnershipResponseSuccess)

export const getSourceOwnershipUrl = (subsector: string,
    sourceId: number,) => {




  return `/subsectors/${subsector}/sources/${sourceId}/ownership`
}

export const sourceOwnership = async (subsector: string,
    sourceId: number, options?: RequestInit): Promise<sourceOwnershipResponse> => {

  return customFetch<sourceOwnershipResponse>(getSourceOwnershipUrl(subsector,sourceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSourceOwnershipQueryKey = (subsector: string,
    sourceId: number,) => {
    return [
    `/subsectors/${subsector}/sources/${sourceId}/ownership`
    ] as const;
    }


export const getSourceOwnershipQueryOptions = <TData = Awaited<ReturnType<typeof sourceOwnership>>, TError = unknown>(subsector: string,
    sourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSourceOwnershipQueryKey(subsector,sourceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sourceOwnership>>> = ({ signal }) => sourceOwnership(subsector,sourceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: subsector !== null && subsector !== undefined && sourceId !== null && sourceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SourceOwnershipQueryResult = NonNullable<Awaited<ReturnType<typeof sourceOwnership>>>
export type SourceOwnershipQueryError = unknown


export function useSourceOwnership<TData = Awaited<ReturnType<typeof sourceOwnership>>, TError = unknown>(
 subsector: string,
    sourceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sourceOwnership>>,
          TError,
          Awaited<ReturnType<typeof sourceOwnership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSourceOwnership<TData = Awaited<ReturnType<typeof sourceOwnership>>, TError = unknown>(
 subsector: string,
    sourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sourceOwnership>>,
          TError,
          Awaited<ReturnType<typeof sourceOwnership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSourceOwnership<TData = Awaited<ReturnType<typeof sourceOwnership>>, TError = unknown>(
 subsector: string,
    sourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSourceOwnership<TData = Awaited<ReturnType<typeof sourceOwnership>>, TError = unknown>(
 subsector: string,
    sourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sourceOwnership>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSourceOwnershipQueryOptions(subsector,sourceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
