import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.9.25"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories { mavenCentral() }

// The apache/spark:3.5.3 runtime is Java 11 — emit class file version 55.
// Both Kotlin and Java targets must agree (Gradle validates consistency).
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
tasks.withType<KotlinCompile> {
    kotlinOptions { jvmTarget = "11" }
}

dependencies {
    // Spark (+ Scala) is provided by the cluster at runtime — compile against it
    // but do NOT bundle it into the app jar. The Cassandra connector is supplied
    // separately via spark-submit --packages.
    compileOnly("org.apache.spark:spark-sql_2.12:3.5.3")
    // kotlin-stdlib is added by the kotlin plugin as `implementation` and IS
    // shaded into the jar so it reaches the Spark executors.
}

// Produce build/libs/analysis.jar (thin uber-jar: our code + kotlin-stdlib).
tasks.named<ShadowJar>("shadowJar") {
    archiveBaseName.set("analysis")
    archiveClassifier.set("")
    archiveVersion.set("")
}

// --- schema constants codegen ------------------------------------------------
// Parse cassandra/schema.cql and emit co2/Schema.kt with table + column name
// constants, so the Spark job's string references are typo-checked at compile
// time (and autocomplete). Runs before compileKotlin when schema.cql is reachable.
fun buildSchemaKt(cql: String): String {
    val noComments = cql.replace(Regex("--.*"), "")
    val tableRe = Regex(
        "CREATE TABLE(?:\\s+IF NOT EXISTS)?\\s+([\\w.]+)\\s*\\((.*?)\\)\\s*;",
        setOf(RegexOption.DOT_MATCHES_ALL, RegexOption.IGNORE_CASE),
    )
    val ident = Regex("^[a-z_][a-z0-9_]*$")
    val tables = sortedSetOf<String>()
    val cols = sortedSetOf<String>()
    for (m in tableRe.findAll(noComments)) {
        tables += m.groupValues[1].substringAfterLast('.')
        for (raw in m.groupValues[2].lineSequence()) {
            val line = raw.trim().trimEnd(',').trim()
            if (line.isEmpty() || line.uppercase().startsWith("PRIMARY KEY")) continue
            val name = line.substringBefore(' ').substringBefore('\t')
            if (ident.matches(name)) cols += name
        }
    }
    return buildString {
        appendLine("// GENERATED by the generateSchema Gradle task from cassandra/schema.cql.")
        appendLine("// Do not edit by hand — run `gradle generateSchema` to refresh.")
        appendLine("package co2")
        appendLine()
        appendLine("/** Cassandra table names in keyspace climate_trace. */")
        appendLine("object Tables {")
        tables.forEach { appendLine("    const val $it = \"$it\"") }
        appendLine("}")
        appendLine()
        appendLine("/** Column names across all tables (deduplicated) — use instead of raw")
        appendLine(" *  strings so a typo in a Spark column reference fails to compile. */")
        appendLine("object Col {")
        cols.forEach { appendLine("    const val $it = \"$it\"") }
        appendLine("}")
    }
}

tasks.register("generateSchema") {
    description = "Generate src/main/kotlin/co2/Schema.kt from cassandra/schema.cql"
    group = "build"
    doLast {
        val schema = listOf(
            file("/schema/schema.cql"),                     // container mount
            file("$projectDir/../../cassandra/schema.cql"), // host layout
        ).firstOrNull { it.exists() }
        if (schema == null) {
            logger.lifecycle("generateSchema: schema.cql not found; keeping existing Schema.kt")
            return@doLast
        }
        val out = file("$projectDir/src/main/kotlin/co2/Schema.kt")
        val generated = buildSchemaKt(schema.readText())
        if (!out.exists() || out.readText() != generated) {
            out.parentFile.mkdirs()
            out.writeText(generated)
            logger.lifecycle("generateSchema: wrote ${out.name} from ${schema.absolutePath}")
        } else {
            logger.lifecycle("generateSchema: Schema.kt already up to date")
        }
    }
}

tasks.named("compileKotlin") { dependsOn("generateSchema") }
